//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
public partial class DocumentIdentification {
    
    private string standardField;
    
    private string typeVersionField;
    
    private string instanceIdentifierField;
    
    private string typeField;
    
    private bool multipleTypeField;
    
    private bool multipleTypeFieldSpecified;
    
    private System.DateTime creationDateAndTimeField;
    
    /// <remarks/>
    public string Standard {
        get {
            return this.standardField;
        }
        set {
            this.standardField = value;
        }
    }
    
    /// <remarks/>
    public string TypeVersion {
        get {
            return this.typeVersionField;
        }
        set {
            this.typeVersionField = value;
        }
    }
    
    /// <remarks/>
    public string InstanceIdentifier {
        get {
            return this.instanceIdentifierField;
        }
        set {
            this.instanceIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public bool MultipleType {
        get {
            return this.multipleTypeField;
        }
        set {
            this.multipleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MultipleTypeSpecified {
        get {
            return this.multipleTypeFieldSpecified;
        }
        set {
            this.multipleTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreationDateAndTime {
        get {
            return this.creationDateAndTimeField;
        }
        set {
            this.creationDateAndTimeField = value;
        }
    }
}
