#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
using namespace System::Xml::Serialization;
using namespace System;
ref class DocumentIdentification;


/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(Namespace=L"http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"), 
System::Xml::Serialization::XmlRootAttribute(Namespace=L"http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
public ref class DocumentIdentification {
    
    private: System::String^  standardField;
    
    private: System::String^  typeVersionField;
    
    private: System::String^  instanceIdentifierField;
    
    private: System::String^  typeField;
    
    private: System::Boolean multipleTypeField;
    
    private: System::Boolean multipleTypeFieldSpecified;
    
    private: System::DateTime creationDateAndTimeField;
    
    /// <remarks/>
    public: property System::String^  Standard {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::String^  TypeVersion {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::String^  InstanceIdentifier {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::String^  Type {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::Boolean MultipleType {
        System::Boolean get();
        System::Void set(System::Boolean value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlIgnoreAttribute]
    property System::Boolean MultipleTypeSpecified {
        System::Boolean get();
        System::Void set(System::Boolean value);
    }
    
    /// <remarks/>
    public: property System::DateTime CreationDateAndTime {
        System::DateTime get();
        System::Void set(System::DateTime value);
    }
};


inline System::String^  DocumentIdentification::Standard::get() {
    return this->standardField;
}
inline System::Void DocumentIdentification::Standard::set(System::String^  value) {
    this->standardField = value;
}

inline System::String^  DocumentIdentification::TypeVersion::get() {
    return this->typeVersionField;
}
inline System::Void DocumentIdentification::TypeVersion::set(System::String^  value) {
    this->typeVersionField = value;
}

inline System::String^  DocumentIdentification::InstanceIdentifier::get() {
    return this->instanceIdentifierField;
}
inline System::Void DocumentIdentification::InstanceIdentifier::set(System::String^  value) {
    this->instanceIdentifierField = value;
}

inline System::String^  DocumentIdentification::Type::get() {
    return this->typeField;
}
inline System::Void DocumentIdentification::Type::set(System::String^  value) {
    this->typeField = value;
}

inline System::Boolean DocumentIdentification::MultipleType::get() {
    return this->multipleTypeField;
}
inline System::Void DocumentIdentification::MultipleType::set(System::Boolean value) {
    this->multipleTypeField = value;
}

inline System::Boolean DocumentIdentification::MultipleTypeSpecified::get() {
    return this->multipleTypeFieldSpecified;
}
inline System::Void DocumentIdentification::MultipleTypeSpecified::set(System::Boolean value) {
    this->multipleTypeFieldSpecified = value;
}

inline System::DateTime DocumentIdentification::CreationDateAndTime::get() {
    return this->creationDateAndTimeField;
}
inline System::Void DocumentIdentification::CreationDateAndTime::set(System::DateTime value) {
    this->creationDateAndTimeField = value;
}
